//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int AppoinmentID { get; set; }
        [Required(ErrorMessage ="Name is Required")]
        [MinLength(2, ErrorMessage ="At least 2 Character Long")]
        [StringLength(20, ErrorMessage ="Name must be 20 character long")]
        public string ApmntName { get; set; }
        [Required(ErrorMessage ="Phone Number is Required")]
        [MinLength(11, ErrorMessage ="Minimum 11 character")]
        [StringLength(11, ErrorMessage ="Maximum 11 character supported")]
        public string ApmntPhone { get; set; }
        public decimal ApmntPayment { get; set; }
        [DisplayFormat(DataFormatString ="{0:MMM dd, yyyy}")]
        public System.DateTime ApmntDate { get; set; }
        public int DoctorID { get; set; }
        public Nullable<System.DateTime> ApmntMakeDate { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
