//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Bill
    {
        public int BillID { get; set; }
        public string BillNO { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> PatientID { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMM dd, yyyy}")]
        public System.DateTime PrepareDate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMM dd, yyyy}")]
        public System.DateTime DischargeDate { get; set; }
        public Nullable<decimal> RoomCharge { get; set; }
        public Nullable<decimal> PathologyFee { get; set; }
        public Nullable<decimal> DoctorFee { get; set; }
        public Nullable<decimal> OtherFees { get; set; }

        [NotMapped]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public decimal GrandBill { get { return Convert.ToDecimal(PathologyFee + DoctorFee + OtherFees); } }
        public Nullable<decimal> Discount { get; set; }
        [NotMapped]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public decimal NetBill { get { return Convert.ToDecimal(GrandBill - Discount); } }
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
