//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Schedules = new HashSet<Schedule>();
            this.TreatmentDetials = new HashSet<TreatmentDetial>();
        }
    
        public int DoctorID { get; set; }
        public string DoctorCardID { get; set; }
        public string DoctorName { get; set; }
        public string Gender { get; set; }
        public string ContactNumber { get; set; }
        public string DoctorAvatar { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> QualificationID { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> AddeddDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentDetial> TreatmentDetials { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
